updated more files

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,8 +27,16 @@ jobs:
       - name: Install Dependencies
         run: npm install
 
+      - name: List directory before build
+        run: ls -la
+
       - name: Build
         run: npm run build
+
+      - name: List directory after build
+        run: |
+          ls -la
+          ls -la out || echo "out directory not found"
 
       - name: Setup Pages
         uses: actions/configure-pages@v4
